<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository {

    public function findUtilisateursByLogin($login) {
        $qb = $this->createQueryBuilder('u');

       return $qb->where($qb->expr()->andX($qb->expr()->like('u.login', ':login')), $qb->expr()->notLike('u.roles', ':roles'))
            ->setParameter('login', '%' . $login . '%')
            ->setParameter('roles', '%ADMIN%')
            ->getQuery()
            ->getResult();
    }

    public function findAllUtilisateurs() {
        $qb = $this->createQueryBuilder('u');

        return $qb->where($qb->expr()->notLike('u.roles', ':roles'))
            ->setParameter('roles', '%ADMIN%')
            ->getQuery()
            ->getResult();
    }
}
